### ISSUE TITLE
add toggle to disable dot or resource temporarily

### ISSUE THREAD

**Issue by gszr** [gszr/dot#28]
```
fetch:
- url: https://github.com/gszr/dynamic-colors
  to: ~/.dynamic-colors
  as: git
  on: false
```
