### ISSUE TITLE
Add support for fetching resources

### ISSUE THREAD

**Issue by gszr** [gszr/dot#4]
As part of environment bootstrap, it is often needed to clone git repos and download files. Support for this in the spec could look like:
```
fetch:
- url: https://github.com/sos4nt/dynamic-colors/
  to: dots/dynamic-colors
  as: git
- url: https://github.com/vimwiki/vimwiki/tree
  to: dots/vim/pack/plugins/start
  as: git
- url: https://raw.githubusercontent.com/docker/cli/master/contrib/completion/zsh/_docker
  to: dots/zsh/completion/
```
